{% set name = "datefinder" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/akoumjian/datefinder/archive/v{{ version }}.tar.gz
  sha256: 53a7d36f98d2ee9ad35f7327f252b252f21e413a301d2f88d4f44012b15f8237

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - regex >=2017.02.08
    - python-dateutil >=2.4.2
    - pytz

test:
  requires:
    - python {{ python_min }}
  imports:
    - datefinder

about:
  home: https://github.com/akoumjian/datefinder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python module for locating dates inside text.
  doc_url: https://github.com/akoumjian/datefinder
  dev_url: https://github.com/akoumjian/datefinder

extra:
  recipe-maintainers:
    - melonhead901
