schema_version: 1

context:
  name: datefinder
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/akoumjian/datefinder/archive/v${{ version }}.tar.gz
  sha256: 53a7d36f98d2ee9ad35f7327f252b252f21e413a301d2f88d4f44012b15f8237

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - regex >=2017.02.08
    - python-dateutil >=2.4.2
    - pytz

tests:
  - python:
      imports:
        - datefinder
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: A python module for locating dates inside text.
  homepage: https://github.com/akoumjian/datefinder
  repository: https://github.com/akoumjian/datefinder
  documentation: https://github.com/akoumjian/datefinder

extra:
  recipe-maintainers:
    - kellend-git
